
package fr.wedley.clientwebservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoftwareUpdate", targetNamespace = "http://webservices.wedley.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoftwareUpdate {


    /**
     * 
     * @return
     *     returns fr.wedley.clientwebservice.SoftwareLastVersions
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastSoftwareVersions", targetNamespace = "http://webservices.wedley.fr/", className = "fr.wedley.clientwebservice.GetLastSoftwareVersions")
    @ResponseWrapper(localName = "getLastSoftwareVersionsResponse", targetNamespace = "http://webservices.wedley.fr/", className = "fr.wedley.clientwebservice.GetLastSoftwareVersionsResponse")
    public SoftwareLastVersions getLastSoftwareVersions();

}
